# Generated by Django 2.0.5 on 2019-03-20 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition',
            name='assistant_lecturer',
            field=models.CharField(default='', max_length=20, verbose_name='辅助讲师'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='lecturer',
            field=models.CharField(default='', max_length=20, verbose_name='讲师'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='parent_mame',
            field=models.CharField(default='', max_length=20, verbose_name='家长姓名'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='parent_phone',
            field=models.CharField(default='', max_length=20, verbose_name='家长电话'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='salesperson',
            field=models.CharField(default='微信', max_length=20, verbose_name='销售员'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='signUp_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='student_name',
            field=models.CharField(default='', max_length=20, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='audition',
            name='student_phone',
            field=models.CharField(default='', max_length=20, verbose_name='学生电话'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='家庭住址'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='birthday',
            field=models.CharField(default='', max_length=10, verbose_name='学生生日'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='coach',
            field=models.CharField(default='', max_length=200, verbose_name='已报辅导班'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='competition',
            field=models.CharField(default='', max_length=200, verbose_name='竞赛意向'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建档日期'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='hobby',
            field=models.CharField(default='', max_length=200, verbose_name='学生爱好'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='input_person',
            field=models.CharField(default='admin', max_length=20, verbose_name='入库员'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='intention_class',
            field=models.CharField(default='scratch', max_length=50, verbose_name='意向课程'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='maintain',
            field=models.CharField(default='', max_length=20, verbose_name='维护员'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='occupation',
            field=models.CharField(default='', max_length=20, verbose_name='家长职业'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='once_competition',
            field=models.CharField(default='', max_length=200, verbose_name='曾经参加竞赛'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='parent_mame',
            field=models.CharField(default='', max_length=20, verbose_name='家长姓名'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='parent_phone',
            field=models.CharField(default='', max_length=20, verbose_name='家长电话'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='parent_qq',
            field=models.CharField(default='', max_length=20, verbose_name='家长QQ'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='parent_wechat',
            field=models.CharField(default='', max_length=20, verbose_name='家长微信'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='record_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录日期'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='relation',
            field=models.CharField(default='', max_length=10, verbose_name='与家长关系'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='salesperson',
            field=models.CharField(default='微信', max_length=20, verbose_name='销售员'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='school',
            field=models.CharField(default='', max_length=100, verbose_name='所在学校'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='speciality',
            field=models.CharField(default='', max_length=200, verbose_name='学生特长'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_age',
            field=models.CharField(default='', max_length=10, verbose_name='学生年龄'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_gender',
            field=models.CharField(default='', max_length=10, verbose_name='学生性别'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_grade',
            field=models.CharField(default='', max_length=10, verbose_name='学生班级'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_name',
            field=models.CharField(default='', max_length=20, verbose_name='学生姓名'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_phone',
            field=models.CharField(default='', max_length=20, verbose_name='学生电话'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_qq',
            field=models.CharField(default='', max_length=20, verbose_name='学生QQ'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='student_wechat',
            field=models.CharField(default='', max_length=20, verbose_name='学生微信'),
        ),
    ]
